sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: "!Hyz001268"
  aws:
    access-key: // your aws access key
    secret-key: // your aws secret key
    endpoint: s3.us-east-2.amazonaws.com
    bucket: kunhua-takeout
  redis:
    host: localhost
    port: 6379
    database: 0
  wechat:
    appid: wx136dcf959beeb247
    secret: 1d9eb7ded1f3fface54e917ec16e5530
    mchid: 1561414331
    mchSerialNo: 483B3DC35414AD50B1B755BAF8DE9CC7CF407606
    privateKeyFilePath:
    apiV3Key: CZBK51236435wxpay435434323FFDuv3
    weChatPayCertFilePath:
    notify-url: http://21a14d0b.r24.cpolar.top/notify/paySuccess
    refundNotifyUrl: http://21a14d0b.r24.cpolar.top/notify/refundSuccess
  shop:
    address: 广东省广州市天河区新村北街15号
  baidu:
    ak: 0Y7kzjg6dzInaWvACf7DBwsTaGwFEvad