sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: "!Hyz001268"
  aws:
    access-key: AKIAQKPILP7ADXYAWEOU
    secret-key: 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
    endpoint: s3.us-east-2.amazonaws.com
    bucket: kunhua-takeout
